name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [16, 18, 20]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: build package
        run: |
          npm i
          npm run build

      - name: test package
        run: |
          npm run test

  deploy_package:
    needs: build_and_test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v12.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: npm
        run: |
          npm i

      #- name: debug deploy_package
      #  uses: actions/bin/debug@master

      - name: deploy via semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx semantic-release@17
